### ISSUE TITLE
Automatic Move

### ISSUE THREAD

**Issue by ajdin1997** [zeratul0/aiurbot#7]
I have noticed, the bot when skip users, move them automatically to 1 place, do you plan to add option to set which place user gets moved and how do i change it manually. Thanks.

**Comment by zeratul0** [comment]
The bot will only move people if their song gets skipped due to unavailability or similar reasons. I can try to implement an option like this soon. In the meantime, you can change this manually, see line 2444 here: https://github.com/zeratul0/aiurbot/blob/d32ef75b65d3853c64383d22957799b9b11e0b73/index.js#L2444

The second argument is the index of the waitlist the DJ should be moved to. I can't remember if plug handles this well when the waitlist is too small (e.g. moving someone to position 6 when there are 3 people on the waitlist) but this should be easy to do.
